### ISSUE TITLE
Bug: MQ error when subscribing path is long

### ISSUE THREAD

**Issue by quwenjie** [CoLearn-Dev/colink-server-dev#30]
This bug is discovered when I call cl.get_variable with a slightly long key, and it reduces to an MQ subscribe problem.
```python
cl=CoLink(addr,jwt)
key="".join(random.choices(string.ascii_letters + string.digits, k=188))
cl.subscribe(key, None)
```
This code throws an gRPC error:
```
"MQ Bind Error: protocol error: AMQP hard error: FRAME-ERROR: FRAME_ERROR - cannot decode
```
I discovered that with  key length<=187 nothing happens, but with any key len>=188 the above error always occur.

**Comment by stneng** [comment]
https://github.com/CoLearn-Dev/colink-server-dev/pull/31
